AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: HW2 Lambda
Resources:
  Lambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./search-photos
      Description: "Lambda function for search photo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::315539653047:role/service-role/search-photos-role-sqw3jmbr"
      Environment:
        Variables:
          REGION: us-east-1
  Lambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index-photos
      Description: "Lambda function for index photo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::315539653047:role/service-role/index-photos-role-4aq5jjuv"
      Environment:
        Variables:
          REGION: us-east-1